# Development Dockerfile for OAuth2 Server
FROM node:25-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci && npm cache clean --force

RUN addgroup -g 1001 -S nodejs && \
    adduser -S nestjs -u 1001 && \
    chown -R nestjs:nodejs /app
USER nestjs

# Expose port
EXPOSE 4000

# Start the application in development mode
CMD ["npm", "run", "start:dev"]
