FROM node:25-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci && npm cache clean --force

RUN addgroup -g 1001 -S nodejs && \
    adduser -S nestjs -u 1001 && \
    chown -R nestjs:nodejs /app
USER nestjs

EXPOSE 3000 9229

CMD ["npm", "run", "start:dev"]
